In [7]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr[1::2])

[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
matA=np.array([
    [3,4],[5,2]
])

In [10]:
matB=np.array([
    [7,9],[1,4]
])

In [14]:
matA*matB == matA@matB

array([[False, False],
       [False, False]])

In [18]:
arr=np.array([80,50,60,25,32,15,70,92])
x=np.max(arr)
ind=np.where (arr==x)
print(f"Max is {x} at index {ind}")

Max is 92 at index (array([7]),)


In [19]:
matA[:,::-1]

array([[4, 3],
       [2, 5]])

In [20]:
lst=np.array([5,6,1,8,9,7,32,50,85,64])
print(lst)

[ 5  6  1  8  9  7 32 50 85 64]


In [21]:
print(lst[0])
print(lst[-1])

5
64


In [22]:
print(lst[::-1])

[64 85 50 32  7  9  8  1  6  5]


In [23]:
print(lst[::2])

[ 5  1  9 32 85]


In [24]:
matc=np.array([
    [5,7,9],[6,2,9],[3,8,7]
])

In [25]:
matc[1]

array([6, 2, 9])

In [26]:
lst+100

array([105, 106, 101, 108, 109, 107, 132, 150, 185, 164])

In [27]:
lst*5

array([ 25,  30,   5,  40,  45,  35, 160, 250, 425, 320])

In [35]:
print(np.sum(lst))
print(np.mean(lst))
print(np.max(lst))
print(np.min(lst))

267
26.7
85
1


In [29]:
print(matc[:,1])

[7 2 8]


In [30]:
matA+matB

array([[10, 13],
       [ 6,  6]])

In [32]:
matA @ matB

array([[25, 43],
       [37, 53]])